apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: httpd
          image: httpd:alpine3.18
            #command: ["/bin/bash", "-c"]  # override the default command
            #args: ["sleep 5; exit 1"] # sleep for 30 seconds then exit with an error
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

